### ISSUE TITLE
Problems_ARGProfile

### ISSUE THREAD

**Issue by cristoyerenahs** [genomicepidemiology/ARGprofiler#3]
Hello. 
My name is Cristopher Yerena. I am trying to use the ARGprofile pipeline. At the moment of "run" , it appears the following message:

![image](https://github.com/genomicepidemiology/ARGprofiler/assets/60819833/4118ccfe-0a42-481b-92dc-f982e14bbdb4)

Could you help me?

I installed fastq-dl from Anaconda.org and change the number id of paired -end.

Thanks

**Comment by cristoyerenahs** [comment]
Hello.

Thanks for the answer. I have installed the kma tool in my system, it "run" in a different way compared to the past message.

Yes, I have installed the snakemake workflow management, but I have the next problem.

![image](https://github.com/genomicepidemiology/ARGprofiler/assets/60819833/75e26c24-5336-4d61-8356-56ca4e39c1d7)

Could you help me?

Thanks

**Comment by blackadder901** [comment]
Hello! Sorry for the late response.
Can you walk me though the installation process? I assume you are cloning the repository and then installing the environment with the following command "mamba env create --name argprofiler --file rules/environment_argprofiler.yaml"?

Niki

**Comment by cristoyerenahs** [comment]
Good afternoon, Nikki,

Thanks for the answer and sorry for the delay.

I am trying to install and use the pipeline in my EC2 instance (Ubuntu 20)

According the instructions of the Github:


  1.
Clone git clone https://github.com/genomicepidemiology/ARGprofiler.git


  1.
Install Snakemake
mamba create -c conda-forge -c bioconda -n snakemake snakemake


  1.
mamba activate snakemake


  1.
snakemake --help

        4. HPC
        snakemake --profile profile_argprofiler


  1.
After running....(image attached)

Could you help me?

Pd. I have another Virtual machine but the I can t install snakemake for cache unwriting stuff...

Thanks


Enviado do Outlook<http://aka.ms/weboutlook>
________________________________
De: blackadder901 ***@***.***>
Enviado: quinta-feira, 4 de abril de 2024 09:49
Para: genomicepidemiology/ARGprofiler ***@***.***>
Cc: cristoyerenahs ***@***.***>; Author ***@***.***>
Assunto: Re: [genomicepidemiology/ARGprofiler] Problems_ARGProfile (Issue #3)


Hello! Sorry for the late response.
Can you walk me though the installation process? I assume you are cloning the repository and then installing the environment with the following command "mamba env create --name argprofiler --file rules/environment_argprofiler.yaml"?

Niki

**Comment by cristoyerenahs** [comment]
Good afternoon, Nikki,

Thanks for the answer. I also tried to install the pipeline under your instructions:


  1.
Clone git clone https://github.com/genomicepidemiology/ARGprofiler.git


  1.
mamba env create --name argprofiler --file rules/environment_argprofiler.yaml


  1.  The env began to run....but I attached the results.

Enviado do Outlook<http://aka.ms/weboutlook>
________________________________
De: blackadder901 ***@***.***>
Enviado: quinta-feira, 4 de abril de 2024 09:49
Para: genomicepidemiology/ARGprofiler ***@***.***>
Cc: cristoyerenahs ***@***.***>; Author ***@***.***>
Assunto: Re: [genomicepidemiology/ARGprofiler] Problems_ARGProfile (Issue #3)


Hello! Sorry for the late response.
Can you walk me though the installation process? I assume you are cloning the repository and then installing the environment with the following command "mamba env create --name argprofiler --file rules/environment_argprofiler.yaml"?

Niki

**Comment by blackadder901** [comment]
Hello there,

If I understand correctly you are trying to run the pipeline on a clean cloud instance. 

You don't need to install Snakemake! What you need to do is to install either mamba or micromamba in order to create and activate the environment we provide (The environment provides the software to run the pipeline).

Use this guide to install micromamba (https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html).

If the installation is successful then you can do the following:
1.mamba env create --name argprofiler --file rules/environment_argprofiler.yaml
2.mamba activate argprofiler
3.snakemake --profile profile_argprofiler

From then on you should be able to execute the workflow with no issues!

I hope this helpes.

Best regards,
Niki
