### ISSUE TITLE
Where can I found the manual?

### ISSUE THREAD

**Issue by bioinfogini** [genomicepidemiology/ARGprofiler#5]
Hello there, I am sorry for the very basic question but, where can be found the manual, or at least the --help for ARGprofiler?
I checked your github and paper, but I could not obtain no clear guidelines. 
I am testing your pipeline and I need it just partially - my case is I just need it from the mapping and alignement, but it is not clear to me.
Any advice?
Thanks

**Comment by hmmartiny** [comment]
Hi @bioinfogini ,

Your question is a bit unclear, but if you only want specific parts of the pipeline, you need to tell Snakemake that. Snakemake has the flag `--until` that runs the pipeline until it reaches the specified rules or files. You can specify multiple rules here! 

Find the name of the rules you want the pipeline to run until to and do a dry-run with `-n` to see which files are created. Afterward, you can remove the `-n` flag and produce your desired output!

**Comment by bioinfogini** [comment]
Allow me rephrase it:

I do not know how to use your pipeline. 
I do not know which commands it  includes, and listing them with Snakemake does not help in understanding what I can use them for, as these info are not reported. 
Your paper and Github **lacks** of step by step instructions on how to use ARGprofiler.
The only guide I could find was on Figure 1 of your paper, where (some?) commands are mentioned. If I try to call it them, the mamba env feedbacks the features available, but it's completely unrelated to snakemake.

Where I can look for an example or a manual? 
Thanks
