### ISSUE TITLE
Running ARGprofiler Locally

### ISSUE THREAD

**Issue by ujennyc** [genomicepidemiology/ARGprofiler#6]
Hi, I am using my MacBook Air M1 laptop for ARGprofiler installation.

I first installed miniforge with Homebrew by running "brew install miniforge",
then cloned the ARGprofiler GitHub repository to my laptop's desktop directory.

I later on created a mamba environment, 
"mamba env create --name argprofiler --file rules/environment_argprofiler.yaml",  
in the ARGprofiler directory.

When I try to activate the environment by commanding "mamba activate argprofiler", it will show the message as follow:
"Run 'mamba init' to be able to run mamba activate/deactivate
and start a new shell session. Or use conda to activate/deactivate."

However, if I run "mamba init" and start a new shell session to activate the environment by commanding "mamba activate argprofiler", it will show the "Run 'mamba init'..." message again.

Hence I would like to ask is there any possible causes for this kind of situation? Thank you!

**Comment by bioinfogini** [comment]
HI @ujennyc ,
I dont know if it could work for you, but if I launch it with conda instead of with mamba works the same for me.
Hope it helps

**Comment by ujennyc** [comment]
Thank you @bioinfogini ! I tried to launch it with conda but encountered the same issue as mamba, but I later found [this answer](https://github.com/idaholab/moose/discussions/24688#discussioncomment-9381214) and solved this issue by running "mamba init zsh" instead of "mamba init".

However, I am facing a new issue when I try to run Snakemake (snakemake --profile profile_argprofiler), multiple errors came up with the same message "one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!". Give one as example:

```
Error in rule fetch_db_mOTUs:
    jobid: 4
    output: prerequisites/db_motus/db_mOTU_v3.0.1.tar.gz
    shell:
        
        /usr/bin/time -v --output=prerequisites/db_motus/fetch_mOTUs.bench wget https://zenodo.org/records/5140350/files/db_mOTU_v3.0.1.tar.gz -P prerequisites/db_motus
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
``` 

I am a beginner and would be grateful if there's any suggestions, thanks!

**Comment by bioinfogini** [comment]
Hi @ujennyc  great to hear you solved it!
I am now stuck in your same error, discussion ongoing [here](https://github.com/genomicepidemiology/ARGprofiler/issues/4) 

I got the suggestion of running 
snakemake --profile profile_argprofiler -R fetch_db_mOTUs

Did not work for me but maybe you will be luckier :)

**Comment by ujennyc** [comment]
Thanks @bioinfogini ! Unfortunately it didn't work for me as well, and I think I'm facing more problems than you, since I can't find the two files mentioned in your [discussion](https://github.com/genomicepidemiology/ARGprofiler/issues/4#issuecomment-2133211400) (db_mOTU_v3.0.1.tar.gz & db_mOTU_DB_CEN.fasta).
For my directory ```~/ARGprofiler/prerequisites/db_motus/``` , there is only a "README.md" file. The situation is the same in my ```~/ARGprofiler/prerequisites/db_panres/```  directory too :(

**Comment by ujennyc** [comment]
An update on how the issue was fixed:

I modified the scripts in the "rules" directory. For the shells that included "/usr/bin/time", I changed them all to "gtime", and it worked on my local MacOS.
